apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-prometheus-0
  namespace: monitoring
spec:
  storageClassName: manual
  volumeName: pv-prometheus
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data-loki-0
  namespace: monitoring
spec:
  storageClassName: manual
  volumeName: pv-loki
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
